name = "podcast"
main = "src/index.ts"
compatibility_date = "2026-05-01"

[[d1_databases]]
binding = "DB"
database_name = "podcast"
database_id = "9dff998a-a064-470d-8cf0-3949f03e91e5"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ai-nuggets-episodes"

[vars]
ALLOWED_PODCASTS = "affinity-matured"
